### ISSUE TITLE
Sorry, it's a RentIt-Worlds bug as I don't have a discord and can only find you here!

### ISSUE THREAD

**Issue by uouiiu** [TrueMB/RentIt#20]
[04:15:38 ERROR]: Could not pass event GuiClickEvent to RentIt-Worlds v1.6.0
java.lang.NoSuchMethodError: 'org.bukkit.craftbukkit.inventory.CraftInventoryView me.truemb.rentitworlds.anvilgui.version.Wrapper1_21_R1$AnvilContainer.getBukkitView()'
        at RentIt-Worlds-1.6.0.jar/me.truemb.rentitworlds.anvilgui.version.Wrapper1_21_R1$AnvilContainer.getBukkitInventory(Wrapper1_21_R1.java:149) ~[RentIt-Worlds-1.6.0.jar:?]
        at RentIt-Worlds-1.6.0.jar/me.truemb.rentitworlds.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:173) ~[RentIt-Worlds-1.6.0.jar:?]
        at RentIt-Worlds-1.6.0.jar/me.truemb.rentitworlds.anvilgui.AnvilGUI.access$1000(AnvilGUI.java:38) ~[RentIt-Worlds-1.6.0.jar:?]
        at RentIt-Worlds-1.6.0.jar/me.truemb.rentitworlds.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:684) ~[RentIt-Worlds-1.6.0.jar:?]
        at RentIt-Worlds-1.6.0.jar/me.truemb.rentitworlds.listener.GuiClickListener.onGuiClick(GuiClickListener.java:222) ~[RentIt-Worlds-1.6.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor484.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2301-a43711d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at RentIt-Worlds-1.6.0.jar/me.truemb.rentitworlds.listener.GuiListener.onClick(GuiListener.java:65) ~[RentIt-Worlds-1.6.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor485.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2301-a43711d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3298) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1574) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1503) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1355) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

This is an error that occurs when the plugin clicks on Custom Info Text.

**Comment by TrueMB** [comment]
You are right, a dependency that I am using in the plugins needs to be updated for 1.21.1.
I didn't realize it until now. Thanks for the report!

I will close it here. It will be in the next version.
